In [4]:
import numpy as np
import time

In [12]:
arr = np.array([1,2,3,4,5])
print(arr,type(arr))

[1 2 3 4 5] <class 'numpy.ndarray'>


In [16]:
#execution time
#size = 100_000_000
size = 1_000_000
py_list = list(range(size))
start =time.time()
sq_list =[x**2 for x in py_list]
end = time.time()
print(f"python list time is {end -start} seconds")

np_arr =np.array(py_list)
start =time.time()
sq_array = np_arr **2
end = time.time()
print(f"numpy array time is {end -start} seconds")

python list time is 1.9121041297912598 seconds
numpy array time is 0.12476181983947754 seconds


In [17]:
#memory
import sys

print(f"python list size is ={sys.getsizeof(py_list) * len(py_list)} bytes")

print(f"numpy array size is ={np_arr.nbytes} bytes")

python list size is =8000056000000 bytes
numpy array size is =8000000 bytes


In [22]:
# create -from lists 

arr1 =np.array ([1,2,3,4,5])
print(arr1, type(arr1), arr1.dtype, arr1.shape)

arr2 =np.array ([1,2,3,4,5,"prime"])
print(arr2, type(arr2), arr2.dtype, arr2.shape)

arr2D =np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
print(arr2D, type(arr2D), arr2D.dtype, arr2D.shape)

[1 2 3 4 5] <class 'numpy.ndarray'> int64 (5,)
['1' '2' '3' '4' '5' 'prime'] <class 'numpy.ndarray'> <U21 (6,)
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]] <class 'numpy.ndarray'> int64 (4, 3)


In [29]:
# create
arr1 =np.zeros((2,3) ,dtype="int64") #prefill
print(arr1, arr1.shape)

arr2 =np.ones((5,))
print(arr2, arr2.shape)

arr3 =np.full((3,4),100)
print(arr3, arr3.shape)

arr4 =np.eye(3)
print(arr4, arr4.shape)

arr5 =np.arange(0,11,2)
print(arr5, arr5.shape)

arr6 =np.linspace(1,100,4)
print(arr6, arr6.shape)

[[0 0 0]
 [0 0 0]] (2, 3)
[1. 1. 1. 1. 1.] (5,)
[[100 100 100 100]
 [100 100 100 100]
 [100 100 100 100]] (3, 4)
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]] (3, 3)
[ 0  2  4  6  8 10] (6,)
[  1.  34.  67. 100.] (4,)


In [76]:
print("\n 2-D ")
arr = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])

print(arr.shape)
print(arr.size)
print(arr.dtype)
print(arr.ndim)

float_arr = arr.astype(np.float64)
print(float_arr,float_arr.dtype)

print("\n 3-D ")
arr = np.array([[[1,2,3],[4,5,6],[7,8,9],[10,11,12]],[[1,2,3],[4,5,6],[7,8,9],[10,11,12]]])

print(arr.shape)
print(arr.size)
print(arr.dtype)
print(arr.ndim)

float_arr = arr.astype(np.float64)
print(float_arr,float_arr.dtype)


 2-D 
(4, 3)
12
int64
2
[[ 1.  2.  3.]
 [ 4.  5.  6.]
 [ 7.  8.  9.]
 [10. 11. 12.]] float64

 3-D 
(2, 4, 3)
24
int64
3
[[[ 1.  2.  3.]
  [ 4.  5.  6.]
  [ 7.  8.  9.]
  [10. 11. 12.]]

 [[ 1.  2.  3.]
  [ 4.  5.  6.]
  [ 7.  8.  9.]
  [10. 11. 12.]]] float64


In [6]:
arr = np.array([[1,2,3],[4,5,6]])
print(arr,arr.shape)

reshaped =arr.reshape(3,2)
print(reshaped,reshaped.shape)

arr1 = np.array([1,2,3,4,5,6])
reshaped1 = arr1.reshape(2,3)
print(arr1,arr1.shape)

flattened = arr.flatten() # 2D => 1D
print(flattened,flattened.shape)


[[1 2 3]
 [4 5 6]] (2, 3)
[[1 2]
 [3 4]
 [5 6]] (3, 2)
[1 2 3 4 5 6] (6,)
[1 2 3 4 5 6] (6,)


In [17]:
# Indexing
arr =np.array([1,2,3,4,5])

print(arr[0])
print(arr[3])

# Fancy Indexing

idx =[0,1,3]
print(arr[idx])

# Boolean Indexing
print(arr[arr>2])
print(arr[arr%2 == 0])
print(arr[arr%2 != 0])

1
4
[1 2 4]
[3 4 5]
[2 4]
[1 3 5]


In [77]:
arr =np.array([1,2,3,4,5])

print(arr[1:4]) # start,end,step
print(arr[1:])
print(arr[:4])
print(arr[:])
print(arr[::2])


[2 3 4]
[2 3 4 5]
[1 2 3 4]
[1 2 3 4 5]
[1 3 5]


In [27]:
# Copy vs View
# Python list
print("Python list")
nums = [1,2,3,4,5]
sub_list = nums[1:3]
print(sub_list)
sub_list[0] =200

print(sub_list)
print(nums)

# numpy arr
print("Numpy arr")
arr = np.array([1,2,3,4,5])
sub_arr = arr[1:3]
print(sub_arr)
sub_arr[0] =200

print(sub_arr)
print(arr)

print("Numpy arr - Copy")
arr1 = np.array([1,2,3,4,5])
sub_arr1 = arr1[1:3].copy()
print(sub_arr1)
sub_arr1[0] =200

print(sub_arr1)
print(arr1)


Python list
[2, 3]
[200, 3]
[1, 2, 3, 4, 5]
Numpy arr
[2 3]
[200   3]
[  1 200   3   4   5]
Numpy arr - Copy
[2 3]
[200   3]
[1 2 3 4 5]


In [78]:
arr = np.array([1,2,3,4,5])
print(arr,arr.dtype)

arr_ = np.array([1,2,3,4,5,"prime"])
print(arr_, arr_.dtype)

arr1 = np.array([1,2,3,4,5,3.14])
print(arr1,arr1.dtype)

arr2 = np.array(["prime",{1,2,3},3.14])
print(arr2,arr2.dtype)

arr3 =np.array([3+5j])
arr4 =np.array([4+3j])

print(arr3+arr4,arr3.dtype)

[1 2 3 4 5] int64
['1' '2' '3' '4' '5' 'prime'] <U21
[1.   2.   3.   4.   5.   3.14] float64
['prime' {1, 2, 3} 3.14] object
[7.+8.j] complex128


In [40]:
# Multi-Dimensional arrays
arr2D = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr2D)

print(np.sum(arr2D))

sum_of_col = np.sum(arr2D,axis =0)
print(sum_of_col)

sum_of_rows = np.sum(arr2D,axis =1)
print(sum_of_rows)

print(arr2D[0:2,1:2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
45
[12 15 18]
[ 6 15 24]
[[2]
 [5]]


In [53]:
arr3D = np.array([[[1,2],[3,4],[5,6]],[[7,8],[9,10],[11,12]]]) # 2*3*2
print(arr3D , arr3D.shape)

#indexing
print(arr3D[1,1,0])

#slicing
print(arr3D[:,0,:])
print(arr3D[:,:,0])

arr3D[:,0,:] = 90 
print(arr3D[:,0,:])
print(arr3D)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]] (2, 3, 2)
9
[[1 2]
 [7 8]]
[[ 1  3  5]
 [ 7  9 11]]
[[90 90]
 [90 90]]
[[[90 90]
  [ 3  4]
  [ 5  6]]

 [[90 90]
  [ 9 10]
  [11 12]]]


In [54]:
# vectorization
arr1 =np.array([1,2,3,4,5])
arr2 = np.array([6,7,8,9,10])

print(arr1+arr2)

[ 7  9 11 13 15]


In [79]:
# broadcasting
arr1 =np.array([1,2,3,4,5])
arr2 = np.array([[1,2,3,4,5],[1,2,3,4,5]])
# arr3 = np.array([[1,2,3,4,5],[1,2,3,4,5],[1,2,3,4,5]]) 

print(arr1.shape)
print(arr2.shape)
print(arr1 +5)
print(arr1+arr2)
# print(arr2+arr3) # would give error

(5,)
(2, 5)
[ 6  7  8  9 10]
[[ 2  4  6  8 10]
 [ 2  4  6  8 10]]


In [63]:
# normalize

arr =np.array([[1,2],[3,4]])

mean =np.mean(arr)
std_dev =np.std(arr)

normalized_arr =(arr -mean)/std_dev
print(normalized_arr)

print(mean)
print(std_dev)

[[-1.34164079 -0.4472136 ]
 [ 0.4472136   1.34164079]]
2.5
1.118033988749895


In [64]:
# Mathematical func

arr = np.array([1,2,3,4,5])

print(np.sum(arr))
print(np.prod(arr))
print(np.min(arr))
print(np.max(arr))
print(np.argmin(arr))
print(np.argmax(arr))

print(np.mean(arr))
print(np.std(arr))
print(np.median(arr))
print(np.var(arr))

15
120
1
5
0
4
3.0
1.4142135623730951
3.0
2.0


In [65]:
arr = np.array([1,2,3,4,5])

print(np.log(arr))
print(np.log2(arr))
print(np.exp(arr))


[0.         0.69314718 1.09861229 1.38629436 1.60943791]
[0.         1.         1.5849625  2.         2.32192809]
[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]


In [69]:
arr = np.array([1,2,3,4,5])

print(np.round(3.14))
print(np.ceil(3.14)) # round up
print(np.floor(3.14))
print(np.trunc(3.14))

arr = np.array([1,2,3,4,5,-6,-8,5,8])

print(np.unique(arr))
print(np.sort(arr))
print(np.abs(arr))

3.0
4.0
3.0
3.0
[-8 -6  1  2  3  4  5  8]
[-8 -6  1  2  3  4  5  5  8]
[1 2 3 4 5 6 8 5 8]


In [ ]:
arr1