In [2]:
import numpy as np
import time

In [5]:
arr = np.array([1,2,4,5,6])
print(arr,type(arr))

[1 2 4 5 6] <class 'numpy.ndarray'>


In [13]:
size =100_000
py_list = list(range(size))
start=time.time()
sq_list = [a**2 for a in py_list]
end= time.time()
print(end - start)

np_arr =np.array(py_list)
start=time.time()
sq_list1 = np_arr **2
end= time.time()
print(end -start)

0.015428543090820312
0.0005676746368408203


In [21]:
arr1 =np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
arr1.shape
arr1.dtype
arr1.size
arr1.ndim

print(arr1[0][1][1])

4


In [23]:
arr2 = np.array([1,2,3,4,5])

print(arr2[2])

idx = [2,3,4]
print(arr2[idx])

arr2[arr2>2]

3
[3 4 5]


array([3, 4, 5])

In [26]:
py_list = [1,2,3,4,5]
copy_list = py_list[1:4]
copy_list[1]=100
print(copy_list)
py_list


[2, 100, 4]


[1, 2, 3, 4, 5]

In [34]:
np_arr = np.array([1,2,3,4,5])
view_arr = np_arr[1:4]
view_arr[1] = 223
view_arr
np_arr

array([  1,   2, 223,   4,   5])

In [47]:
copy_arr =np.array([1,2,3,4,5],dtype = "int")
view_arr1 =copy_arr[1:4].copy()
view_arr1[1]=220
view_arr1
copy_arr

array([1, 2, 3, 4, 5])

In [48]:
arr1 = np.array([1+2j])
arr2 =np.array([2+4j])
print(arr1+arr2)


[3.+6.j]


In [50]:
copy_arr.astype("float")

array([1., 2., 3., 4., 5.])

In [60]:
arr1 =np.array([1,2,3,4,5])
arr2 = np.array([[1,2,3,4,5],[1,2,3,6,7]])
arr1+arr2

array([[ 2,  4,  6,  8, 10],
       [ 2,  4,  6, 10, 12]])

In [62]:
arr3D = np.array([[[1,2],[3,4],[5,6]],[[7,8],[9,10],[11,12]]]) # 2*3*2

print(arr3D[0,2,1])

6
